### ISSUE TITLE
AssertionError when adding a hotkey without modifier

### ISSUE THREAD

**Issue by gcfrxbots** [timeyyy/system_hotkey#14]
When attempting to create a hotkey using 

```hk.register("f", callback=item)```
I'm given an AssertionError
```Unhandled exception in thread started by <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x00000255D11E8B38>>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\system_hotkey\util.py", line 37, in call_functions
    func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\system_hotkey\system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
AssertionError
```

but it works fine if I instead try ```hk.register(("control", "f"), callback=item)```

Can I not register a single key as a hotkey?

**Comment by timeyyy** [comment]
Did you try doing `hk.register("f",), callback=item)`?

the comma makes it a tuple. or just `["f"]`

If this works consider making a pr with an example
