### ISSUE TITLE
NameError: name 'SystemHotkeys' is not defined

### ISSUE THREAD

**Issue by imv7** [timeyyy/system_hotkey#15]
```
from system_hotkey import SystemHotkey
hk = SystemHotkeys()
hk.register(('control', 'shift', 'h'), callback=lambda:print("Easy!"))
```

C:\Users\IgorMonteiroVieira\Desktop>python ahk.py
Traceback (most recent call last):
  File "ahk.py", line 2, in <module>
    hk = SystemHotkeys()
NameError: name 'SystemHotkeys' is not defined

**Comment by imv7** [comment]
Should be SystemHotKey instead of "s"? Thanks

**Comment by timeyyy** [comment]
This issue is fixed in the latest readme.
