### ISSUE TITLE
Extremely unstable with Qt on Windows

### ISSUE THREAD

**Issue by Darayavaush** [timeyyy/system_hotkey#16]
```
from PySide2 import QtWidgets, QtGui
import time
from system_hotkey import SystemHotkey

def fill():
    time.sleep(1)
    box.setPlainText('a' * 1000)

app = QtWidgets.QApplication([])
box = QtWidgets.QPlainTextEdit()
box.show()
QtWidgets.QShortcut(QtGui.QKeySequence("Ctrl+n"), box, fill)

hk = SystemHotkey(verbose=True)
hk.register(('alt', 'n'), callback=lambda x: fill())
app.exec_()
```

This very simple app creates a text box and attaches two hotkeys that fill it with 'a' * 1000 after a 1-second delay. The built-in Qt hotkey functionality (attached to ctrl+n) does this with no problem; system_hotkey, however, causes a crash every time. Reducing the length of the text or removing the delay causes the crash to occur more rarely.

I am on Windows 7 x64. Tested with Python 3.8 with Pyside2 (Qt5) and Python 3.4 with Pyside (Qt4) with identical results.

**Comment by timeyyy** [comment]
Qt widgets are not thread safe and should not be accessed from any thread but the main thread (see the Qt documentation for more details).

The callback in our system is being run in another thread than the qt thread. Most ui libraries have this limitation where you need to update the ui from the same thread. Shortcut might handle this for you. That would also explains the indeterministic behaviour.

The solution would be to use a callback that tells the qt main thread to run the fill function

**Comment by Darayavaush** [comment]
That helped, thanks.
